import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

import Header from "../components/ui/Header";
import Footer from "../components/ui/Footer";

const clashDisplay = localFont({
  variable: "--font-clash-display",
  src: "../../public/fonts/ClashDisplay-Variable.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${clashDisplay.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
